parameters:
    facebook_provider.class: Application\userBundle\Security\User\Provider\FacebookProvider

services:
#    login_listener:
#            class: Application\userBundle\Listener\LoginListener
#            arguments: ["@security.context", "@doctrine","@router"]
#            tags:
#              - { name: kernel.event_listener, event: security.interactive_login }
#              - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }           
    acme_user.registration.form.type:
            class: Application\userBundle\Form\Type\RegistrationFormType
            arguments: [%fos_user.model.user.class%]
            tags:
                - { name: form.type, alias: app_user_registration }
    facebook_provider:
            class: %facebook_provider.class%
            arguments : [ "@fos_facebook.api","@fos_user.user_manager","@validator","@service_container",%fos_user.model.user.class% ]
            
                
    